# Generated by Django 5.1.2 on 2024-10-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders_words', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='folder',
        ),
    ]
