# Generated by Django 5.1.2 on 2024-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders_words', '0007_translate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='voice',
            field=models.FileField(default=1, upload_to='voices/'),
            preserve_default=False,
        ),
    ]
