# Generated by Django 5.2 on 2025-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.BooleanField(default=0),
        ),
    ]
